model_name: efficientnet_b0_mil
classes: [0, 1, 2, 3, 4, 5]
device: cuda:0
learner_type: mil
val_every: 0.5
epochs: 20
batch_size: 8
window_size: 256
data_root: ~/data/patches
csv_name: dev.csv
crop_csv: master_patches.csv
folds: [0]
num_samples: 12
max_patches: 12

# Loss Functions
criteria:
  class_criterion:
    type: ce_loss
    params:
      weight:

# Networks
network:
  type: efficientnet_pytorch
  params:
    advprop: False
    drop_connect_rate: 0.2
    dropout: 0.5
    model_name: efficientnet-b0

# Optimizer
optimizer:
  type: Adam
  params:
    lr: 0.0001
    weight_decay: 0.00001

# Scheduler
# TODO: no cooldown?
scheduler:
  type: ReduceLROnPlateau
  params:
    patience: 4
    verbose: True
    min_lr: 0.0000001
    factor: 0.2

transforms:
  train:
    - Rotate: {p: 1.0}
    - RandomCrop: {height: 224, width: 224}
    - HorizontalFlip: {p: 0.5}
    - VerticalFlip: {p: 0.5}
    - Normalize: {mean: [0.406, 0.456, 0.485], std: [0.225, 0.224, 0.229]}
#     - ToTensor: {}
  val:
    - CenterCrop: {height: 224, width: 224}
    - Normalize: {mean: [0.406, 0.456, 0.485], std: [0.225, 0.224, 0.229]}
#     - ToTensor: {}

#To visualize everything, leave this blank. To visualize nothing, set this to empty list [].
# Logging
logging:
  log_dir: tensorboard
  classes:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
